services:
  coordinator:
    build: .
    container_name: coordinator
    ports:
      - "8080:8080"
    command: >
      java -jar mr-app-1.0.jar coordinator http://coordinator:8080
    networks:
      - mrnet

  worker:
    build: .
    depends_on:
      - coordinator
    command: >
      sh -c "sleep 3 && java -jar mr-app-1.0.jar worker http://coordinator:8080 http://$(hostname):8090"
    networks:
      - mrnet

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - mrnet

  minio-init:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      sh -c "until mc alias set myminio http://minio:9000 minioadmin minioadmin 2>/dev/null; do
               echo 'Waiting for MinIO...';
               sleep 2;
             done;
             echo 'MinIO alias set successfully.';
             mc mb myminio/jobs || true"
    networks:
      - mrnet

networks:
  mrnet:
    driver: bridge

volumes:
  minio_data: