apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mr-cluster.fullname" . }}-coordinator
spec:
  replicas: {{ .Values.replicaCount.coordinator }}
  selector:
    matchLabels:
      app: {{ include "mr-cluster.fullname" . }}-coordinator
  template:
    metadata:
      labels:
        app: {{ include "mr-cluster.fullname" . }}-coordinator
    spec:
      serviceAccountName: coordinator-sa

      initContainers:
      - name: wait-for-elasticsearch
        image: curlimages/curl:8.4.0
        command:
          - sh
          - -c
          - |
            echo "Waiting for Elasticsearch cluster to be at least yellow..."
            until curl --silent --fail \
              "http://{{ include "mr-cluster.fullname" . }}-elasticsearch:9200/_cluster/health?wait_for_status=yellow&timeout=1s"; do
              echo "  Elasticsearch not ready yet, retrying in 5s..."
              sleep 5
            done
            echo "Elasticsearch is ready!"

      containers:
        - name: coordinator
          image: "{{ .Values.image.coordinator.repository }}:{{ .Values.image.coordinator.tag }}"
          command:
            - java
            - -jar
            - mr-app-{{ .Chart.AppVersion }}.jar
            - --logs
            - http://{{ include "mr-cluster.fullname" . }}-elasticsearch:9200{{ .Values.coordinator.logsIndexURI }}
            - coordinator
            - http://0.0.0.0:{{ .Values.coordinator.service.port }}
          ports:
            - containerPort: {{ .Values.coordinator.service.port }}
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CONFIGMAP_NAME
              value: "{{ include "mr-cluster.fullname" . }}{{ .Values.coordinator.workersConfigMap.nameSuffix }}"
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.coordinator.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 2
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.coordinator.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3

