apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mr-cluster.fullname" . }}-elasticsearch
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ default "" .Values.elasticsearch.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.elasticsearch.persistence.size }}
