apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mr-cluster.fullname" . }}-elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "mr-cluster.fullname" . }}-elasticsearch
  template:
    metadata:
      labels:
        app: {{ include "mr-cluster.fullname" . }}-elasticsearch
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: elasticsearch
        image: "{{ .Values.elasticsearch.image.repository }}:{{ .Values.elasticsearch.image.tag }}"
        env:
        - name: discovery.type
          value: "single-node"
        - name: xpack.security.enabled
          value: "false"
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        ports:
        - containerPort: 9200
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ include "mr-cluster.fullname" . }}-elasticsearch
