apiVersion: v1
kind: Service
metadata:
  name: {{ include "mr-cluster.fullname" . }}-elasticsearch
spec:
  type: ClusterIP
  selector:
    app: {{ include "mr-cluster.fullname" . }}-elasticsearch
  ports:
  - port: 9200
    targetPort: 9200
