apiVersion: v1
kind: Service
metadata:
  name: {{ include "mr-cluster.fullname" . }}-kibana
spec:
  type: {{ .Values.kibana.service.type }}
  selector:
    app: {{ include "mr-cluster.fullname" . }}-kibana
  ports:
  - port: {{ .Values.kibana.service.port }}
    targetPort: {{ .Values.kibana.service.port }}
    {{- if eq .Values.kibana.service.type "NodePort" }}
    nodePort: 30561
    {{- end }}
