apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mr-cluster.fullname" . }}-minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "mr-cluster.fullname" . }}-minio
  template:
    metadata:
      labels:
        app: {{ include "mr-cluster.fullname" . }}-minio
    spec:
      containers:
      - name: minio
        image: "{{ .Values.minio.image.repository }}:{{ .Values.minio.image.tag }}"
        args:
        - "server"
        - "/data"
        - "--console-address"
        - ":{{ .Values.minio.service.consolePort }}"
        env:
        - name: MINIO_ROOT_USER
          value: "{{ .Values.minio.credentials.accessKey }}"
        - name: MINIO_ROOT_PASSWORD
          value: "{{ .Values.minio.credentials.secretKey }}"
        ports:
        - name: api
          containerPort: {{ .Values.minio.service.apiPort }}
        - name: console
          containerPort: {{ .Values.minio.service.consolePort }}
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ include "mr-cluster.fullname" . }}-minio
