apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mr-cluster.fullname" . }}-minio
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ default "" .Values.minio.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.minio.persistence.size }}
