apiVersion: v1
kind: Service
metadata:
  name: {{ include "mr-cluster.fullname" . }}-worker
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: {{ include "mr-cluster.fullname" . }}-worker
  ports:
    - name: http
      port: {{ .Values.worker.service.port }}
      targetPort: {{ .Values.worker.service.port }}
